// ---------------------------------------------------------------------------
// ProctorAI — Screen-Review Message Validators (Phase 11)
// ---------------------------------------------------------------------------
//
// Pure parse-and-validate helpers for the screen-review messages the
// service worker receives from the consent overlay (content script) and
// the screen-review module (offscreen document). They replace ad-hoc
// `as` casts with strict runtime checks: every field the handler relies
// on is validated before use, and malformed messages are rejected with
// null instead of being partially trusted.
//
// Unknown extra fields (e.g. `target`, `reason`) are tolerated — only the
// fields each handler actually reads are validated.
//
// No Chrome APIs. No DOM APIs. Fully unit-testable.
// ---------------------------------------------------------------------------

/** Maximum length of a screen-review identifier (backend emits SR-<32 hex>). */
export const MAX_REVIEW_ID_LENGTH = 64

/** Maximum SDP offer size — matches the backend screen-review WS limit. */
export const MAX_SDP_LENGTH = 10_240

/** Maximum ICE candidate size — matches the backend screen-review WS limit. */
export const MAX_CANDIDATE_LENGTH = 1024

/** Consent decision reported by the student overlay. */
export interface ConsentMessage {
  type: 'SCREEN_REVIEW_CONSENT'
  screen_review_id: string
  accepted: boolean
}

/** SDP offer generated by the offscreen WebRTC peer connection. */
export interface OfferMessage {
  type: 'SCREEN_REVIEW_OFFER'
  screen_review_id: string
  sdp: string
}

/** ICE candidate generated by the offscreen WebRTC peer connection. */
export interface IceCandidateMessage {
  type: 'SCREEN_REVIEW_ICE_CANDIDATE'
  screen_review_id: string
  candidate: string
  sdpMid: string | null
  sdpMLineIndex: number | null
}

/** Screen share stopped — by the student ("Stop" button) or by offscreen. */
export interface StoppedMessage {
  type: 'SCREEN_REVIEW_STOP_FROM_STUDENT' | 'SCREEN_REVIEW_STOPPED'
  screen_review_id: string
}

// ---------------------------------------------------------------------------

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value)
}

function isReviewId(value: unknown): value is string {
  return (
    typeof value === 'string' &&
    value.length > 0 &&
    value.length <= MAX_REVIEW_ID_LENGTH
  )
}

/**
 * Validate a student consent message.
 * Requires: exact type, non-empty review_id <= 64 chars, boolean accepted.
 */
export function parseConsentMessage(raw: unknown): ConsentMessage | null {
  if (!isRecord(raw)) return null
  if (raw.type !== 'SCREEN_REVIEW_CONSENT') return null
  if (!isReviewId(raw.screen_review_id)) return null
  if (typeof raw.accepted !== 'boolean') return null
  return {
    type: 'SCREEN_REVIEW_CONSENT',
    screen_review_id: raw.screen_review_id,
    accepted: raw.accepted,
  }
}

/**
 * Validate an SDP offer message.
 * Requires: exact type, non-empty review_id <= 64 chars, non-empty sdp
 * <= 10 KB (matches the backend limit).
 */
export function parseOfferMessage(raw: unknown): OfferMessage | null {
  if (!isRecord(raw)) return null
  if (raw.type !== 'SCREEN_REVIEW_OFFER') return null
  if (!isReviewId(raw.screen_review_id)) return null
  const sdp = raw.sdp
  if (
    typeof sdp !== 'string' ||
    sdp.length === 0 ||
    sdp.length > MAX_SDP_LENGTH
  ) {
    return null
  }
  return {
    type: 'SCREEN_REVIEW_OFFER',
    screen_review_id: raw.screen_review_id,
    sdp,
  }
}

/**
 * Validate an ICE candidate message.
 * Requires: exact type, non-empty review_id <= 64 chars, non-empty
 * candidate <= 1 KB, sdpMid string|null, sdpMLineIndex number|null.
 * Absent (undefined) sdpMid/sdpMLineIndex are normalized to null,
 * matching the previous `?? null` relay behavior.
 */
export function parseIceCandidateMessage(
  raw: unknown
): IceCandidateMessage | null {
  if (!isRecord(raw)) return null
  if (raw.type !== 'SCREEN_REVIEW_ICE_CANDIDATE') return null
  if (!isReviewId(raw.screen_review_id)) return null
  const candidate = raw.candidate
  if (
    typeof candidate !== 'string' ||
    candidate.length === 0 ||
    candidate.length > MAX_CANDIDATE_LENGTH
  ) {
    return null
  }
  const sdpMid = raw.sdpMid ?? null
  if (sdpMid !== null && typeof sdpMid !== 'string') return null
  const sdpMLineIndex = raw.sdpMLineIndex ?? null
  if (sdpMLineIndex !== null && typeof sdpMLineIndex !== 'number') {
    return null
  }
  return {
    type: 'SCREEN_REVIEW_ICE_CANDIDATE',
    screen_review_id: raw.screen_review_id,
    candidate,
    sdpMid,
    sdpMLineIndex,
  }
}

/**
 * Validate a stopped message (student "Stop" button or offscreen track end).
 * Requires: one of the two stopped types, non-empty review_id <= 64 chars.
 */
export function parseStoppedMessage(raw: unknown): StoppedMessage | null {
  if (!isRecord(raw)) return null
  if (
    raw.type !== 'SCREEN_REVIEW_STOP_FROM_STUDENT' &&
    raw.type !== 'SCREEN_REVIEW_STOPPED'
  ) {
    return null
  }
  if (!isReviewId(raw.screen_review_id)) return null
  return {
    type: raw.type,
    screen_review_id: raw.screen_review_id,
  }
}
